### PR TITLE
Use new sidebar (with subsidebar)

### PR DESCRIPTION
**Pull request by EpokK**
Capture d’écran 2020-01-13 à 18 36 56

Manager: @matstaz 
[Test server](https://royal.protonmail.blue)
[Design](https://app.zeplin.io/project/5d5b7ea26986389b1e7b265c/screen/5dfc7b8d2ec4d697546b44ab)

### Requirement

- https://github.com/ProtonMail/react-components/pull/519

Fix https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/60

### CODE REVIEW

**Comment by gandriux** [comment]
It would be good to allocate more space for new sidebar:

**Comment by gandriux** [comment]
Sidebar scrollbar should scroll to Delete and Emil subscription section (right now green scrollbar doesn't change position)
[2020-01-16_10-54-03.zip](https://github.com/ProtonMail/proton-vpn-settings/files/4070157/2020-01-16_10-54-03.zip)

**Comment by nico3333fr** [comment]
@EpokK Or maybe remove ellipsis and let content come to another line? (it is easy to do, so this is why I propose)

**Comment by matstaz** [comment]
@gandriux we unfortunately cannot do anything. It used to be the same UX before when it was located on the right... I will need to think how we can change the UX to accomodate the section highlighted when scrolled all the way at the bottom

**Comment by matstaz** [comment]
@gandriux more space is coming. I asked the team to extend the sidebar to 220px instead of 180px. This is to be consistent across all apps

**Pull request merged**
